// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"OnlineAvatar","status":true,"description":"Firebaseを使ってプレイヤーをオンライン同期します。","parameters":{"apiKey":"AIzaSyBSfNtdad-mYhVuN52PdBrMooS7nt1XTBI","authDomain":"trpg-f3ce3.firebaseapp.com","databaseURL":"https://trpg-f3ce3.firebaseio.com","avatarEvent":"1","syncSwitchStart":"11","syncSwitchEnd":"20","syncVariableStart":"11","syncVariableEnd":"20"}}
];
